import type { AppProps } from 'next/app'
import Head from 'next/head'
//import '../../styles/_globals.scss'

export function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <div className="app">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300&display=swap" rel="stylesheet" />
      </Head>
      <header>
        <div className="headerContainer">
          <div className="headerTop"><a>top header</a></div>
          <div>bottom header</div>
        </div>
      </header>
      <main>
        <div className="mainContent">
          <Component {...pageProps} />
        </div>
      </main>
      <footer>
        <div className="footerContainer">footer</div>
      </footer>
    </div>
  </>
}
