import '../styles/_globals.scss'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Head from 'next/head'
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false // Tell Font Awesome to skip adding the CSS automatically since it's being imported above

export default function App({ Component, pageProps }) {
    const getLayout = Component.getLayout || ((page) => page)

    return getLayout(
        <div className="app">
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300&display=swap" rel="stylesheet" />
            </Head>
            <Component {...pageProps} />
        </div>
    )
}
